version: "3.9"

services:
    app:
        build: .
        container_name: laravel-app
        env_file: .env
        ports:
            - "127.0.0.1:8080:80"     # -> accéder à Laravel via http://localhost:8080 ou http://<VPS_IP>:8080
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - ./:/app:cached
            - vendor-data:/app/vendor
            - node-modules:/app/node_modules
        environment:
            # variables utiles pour dev / debug
            SKIP_DB_WAIT: "0"
        restart: unless-stopped

    db:
        image: mysql:8.0
        container_name: mysql-db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
            interval: 5s
            timeout: 3s
            retries: 20
        restart: unless-stopped

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8081:80"   # phpMyAdmin: http://localhost:8081
        depends_on:
            - db
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        container_name: redis
        volumes:
            - redisdata:/data
        restart: unless-stopped

volumes:
    dbdata:
    vendor-data:
    node-modules:
    redisdata:
