services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        container_name: school-app
        env_file: .env
        volumes:
            - .:/var/www/html
        depends_on:
            mysql:
                condition: service_healthy

    nginx:
        image: nginx:1.25-alpine
        container_name: school-nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: school-mysql
        command: --default-authentication-plugin=mysql_native_password --sql-mode=""
        environment:
            MYSQL_DATABASE: school_db
            MYSQL_USER: school_user
            MYSQL_PASSWORD: school_pass
            MYSQL_ROOT_PASSWORD: rootpass
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpass"]
            interval: 5s
            timeout: 3s
            retries: 20

volumes:
    mysql_data:
