name: CI/CD - Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    name: Build and push image
    runs-on: [ self-hosted, deploy-vps ]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (optional, for multi-arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/school-backend:latest
            ghcr.io/${{ github.repository_owner }}/school-backend:${{ github.sha }}

  deploy:
    name: Deploy (on self-hosted runner)
    needs: build_and_push
    runs-on: [ self-hosted, deploy-vps ]
    steps:
      - name: Checkout (for any deploy artifacts)
        uses: actions/checkout@v4

      - name: Pull images and restart services
        run: |
          # aller dans le dossier où est ton docker-compose prod
          cd /home/deploy/apps/school || exit 1

          # s'assurer que docker compose est accessible
          docker compose version

          # pull et redémarrer
          docker compose pull
          docker compose up -d --remove-orphans

          # optional: run migrations (décommenter si voulu)
          # docker compose exec -T app php artisan migrate --force
